title:              A Caminho da Independência Financeira
subtitle:           ... em português
email:              indepfinanceiraemportugal@gmail.com
description:        Um blog onde partilhamos a nossa viagem até alcançarmos independência financeira em Portugal
author:             PortugalSavers
#baseurl:            "IFPT20.github.io"
url:                "https://IFPT20.github.io"

# Social Profiles
twitter_username: PortugalSavers
github_username:
facebook_username:  PortugalSavers
instagram_username:  PortugalSavers
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
